site_name: PDM-Backend

repo_url: https://github.com/pdm-project/pdm-backend
edit_uri: edit/main/docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Open Sans
    code: Fira Code
  logo: https://cdn.jsdelivr.net/gh/pdm-project/pdm@main/docs/assets/logo.svg
  favicon: https://cdn.jsdelivr.net/gh/pdm-project/pdm@main/docs/assets/logo.svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
  - "mkdocs-version-annotations":
      version_added_admonition: "tip"

nav:
  - Home: index.md
  - metadata.md
  - build_config.md
  - hooks.md
  - api.md
  - migration.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - tables
  - toc:
      permalink: "#"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2019 <a href="https://frostming.com">Frost Ming</a>

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pdm-project/pdm-backend
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pdm_project
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Phn8smztpv
